version: '3.7'
services:
  code-push-server:
    image: code-push-server
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/codepush-all-docker.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    volumes:
      - data-redis:/data
    ports:
      - '6379:6379'
volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
